namespace IoCTools.Tools.Cli;

using CommandLine;

/// <summary>
/// Generates .editorconfig rules for suppressing IoCTools diagnostics (CLI-07).
/// </summary>
internal static class SuppressPrinter
{
    public static int Write(
        SuppressCommandOptions options,
        OutputContext output,
        IReadOnlyList<string>? liveDiagnosticIds = null)
    {
        var catalog = DiagnosticCatalog.GetAll();

        // Filter by --severity (default is warning,info)
        var severityFilter = options.Severities ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Warning", "Info" };

        // Filter by --codes (optional explicit picks)
        var codeFilter = options.Codes;

        // Filter entries
        var filtered = catalog.Where(e =>
        {
            // If --live, only include codes actually firing
            if (liveDiagnosticIds != null && !liveDiagnosticIds.Contains(e.Id, StringComparer.OrdinalIgnoreCase))
                return false;

            // If --codes specified, include those (regardless of severity)
            if (codeFilter != null && codeFilter.Count > 0)
            {
                // When both --codes and --severity are specified, OR them
                return codeFilter.Contains(e.Id, StringComparer.OrdinalIgnoreCase) || severityFilter.Contains(e.DefaultSeverity);
            }

            return severityFilter.Contains(e.DefaultSeverity);
        }).ToList();

        if (filtered.Count == 0)
        {
            output.WriteError("No diagnostics match the specified filters.");
            return 1;
        }

        // Group by category
        var grouped = filtered.GroupBy(e => e.Category).OrderBy(g => g.Key);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# IoCTools diagnostic suppressions");
        sb.AppendLine("# Generated by: ioc-tools suppress");
        sb.AppendLine();

        foreach (var group in grouped)
        {
            sb.AppendLine($"# {group.Key}");
            foreach (var entry in group.OrderBy(e => e.Id, StringComparer.Ordinal))
            {
                // Error-severity codes suppressed via --codes get louder comment
                var isErrorExplicitlyOverridden = entry.DefaultSeverity == "Error"
                    && codeFilter != null && codeFilter.Contains(entry.Id, StringComparer.OrdinalIgnoreCase);

                if (isErrorExplicitlyOverridden)
                    sb.AppendLine($"dotnet_diagnostic.{entry.Id}.severity = none  # {entry.Title} — suppressed explicitly (verify this is intentional)");
                else
                    sb.AppendLine($"dotnet_diagnostic.{entry.Id}.severity = none  # {entry.Title}");
            }
            sb.AppendLine();
        }

        var content = sb.ToString().TrimEnd() + Environment.NewLine;

        // Output: stdout by default, --output file with conflict detection
        if (options.OutputPath != null)
        {
            return AppendToFile(options.OutputPath, content, output);
        }

        // JSON mode
        if (output.IsJson)
        {
            var rules = filtered.Select(e => new { e.Id, e.Title, e.Category, e.DefaultSeverity, suppressed = "none" });
            output.WriteJson(new { rules, editorconfig = content });
            return 0;
        }

        // Direct to stdout for piping (not through OutputContext which suppresses in JSON mode)
        Console.Write(content);
        return 0;
    }

    private static int AppendToFile(string path, string content, OutputContext output)
    {
        // Read existing file to check for conflicts
        var existingRules = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var skippedCount = 0;

        if (File.Exists(path))
        {
            var existingLines = File.ReadAllLines(path);
            foreach (var line in existingLines)
            {
                var trimmed = line.Trim();
                if (trimmed.StartsWith("dotnet_diagnostic.IOC", StringComparison.OrdinalIgnoreCase))
                {
                    var dotIndex = trimmed.IndexOf('.', "dotnet_diagnostic.".Length);
                    if (dotIndex > 0)
                    {
                        var ruleId = trimmed.Substring("dotnet_diagnostic.".Length, dotIndex - "dotnet_diagnostic.".Length);
                        existingRules.Add(ruleId);
                    }
                }
            }
        }

        // Filter out already-present rules
        var lines = content.Split(new[] { Environment.NewLine, "\n" }, StringSplitOptions.None);
        var filteredLines = new List<string>();
        foreach (var line in lines)
        {
            if (line.TrimStart().StartsWith("dotnet_diagnostic.IOC", StringComparison.OrdinalIgnoreCase))
            {
                var trimmed = line.Trim();
                var dotIndex = trimmed.IndexOf('.', "dotnet_diagnostic.".Length);
                if (dotIndex > 0)
                {
                    var ruleId = trimmed.Substring("dotnet_diagnostic.".Length, dotIndex - "dotnet_diagnostic.".Length);
                    if (existingRules.Contains(ruleId))
                    {
                        skippedCount++;
                        continue;
                    }
                }
            }
            filteredLines.Add(line);
        }

        var filteredContent = string.Join(Environment.NewLine, filteredLines);
        if (string.IsNullOrWhiteSpace(filteredContent.Replace("#", "").Trim()))
        {
            output.WriteError($"All rules already present in {path}. Nothing to append.");
            return 0;
        }

        File.AppendAllText(path, Environment.NewLine + filteredContent);
        output.WriteError($"Appended to {path}. {skippedCount} existing rules skipped.");
        return 0;
    }
}
