namespace IoCTools.Generator.Tests;

using System.CodeDom.Compiler;
using System.Reflection;
using Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

/// <summary>
/// Regression tests for IoCTools 1.7.3 fixes:
///   IOC997 — array TypedConstant .Value crash in AddTypedConstantDependency
///   TDIAG04 — false positive for services with [GeneratedCode("IoCTools")] constructor
/// </summary>
public sealed class RegressionTests173
{
    #region IOC997 — Array TypedConstant crash

    /// <summary>
    /// Reproduces the pre-1.7.3 crash: when a DependsOn-family attribute has a params Type[]
    /// constructor argument called with multiple types, the compiler stores them as a single
    /// array TypedConstant. The old AddTypedConstantDependency called .Value on an array-kind
    /// TypedConstant which throws "TypedConstant is an array. Use Values property."
    /// </summary>
    [Fact]
    public void IOC997_ArrayTypedConstant_DoesNotThrow()
    {
        // DependsOnExtrasAttribute name starts with "DependsOn" — passes IsDependsOnAttribute.
        // Two types → compiler stores as array TypedConstant in ConstructorArguments.
        var source = @"
using System;
using IoCTools.Abstractions.Annotations;
using IoCTools.Testing.Annotations;

[AttributeUsage(AttributeTargets.Class)]
public sealed class DependsOnExtrasAttribute : Attribute
{
    public DependsOnExtrasAttribute(params Type[] types) { }
}

public interface IFoo { }
public interface IBar { }

[Scoped]
[DependsOnExtras(typeof(IFoo), typeof(IBar))]
public partial class MyService { }

[Cover<MyService>]
public partial class MyServiceTests { }";

        // Must not throw; pre-fix this raised InvalidOperationException: TypedConstant is an array.
        GeneratorTestResult result = default!;
        var act = () => { result = CompileWithCover(source); };
        act.Should().NotThrow("array TypedConstant in DependsOn-family ctor args must be handled without crashing");

        // No IOC997 internal error diagnostic should be emitted.
        result.Diagnostics
            .Where(d => d.Id == "IOC997")
            .Should().BeEmpty("IOC997 should not fire post-fix");
    }

    /// <summary>
    /// Single-type array args (compiler stores as scalar TypedConstant) — existing path still works.
    /// Regression guard: the pre-1.7.3 guard swap must not break the scalar case.
    /// </summary>
    [Fact]
    public void IOC997_SingleTypeArg_StillWorks()
    {
        var source = @"
using System;
using IoCTools.Abstractions.Annotations;
using IoCTools.Testing.Annotations;

[AttributeUsage(AttributeTargets.Class)]
public sealed class DependsOnExtrasAttribute : Attribute
{
    public DependsOnExtrasAttribute(params Type[] types) { }
}

public interface IFoo { }

[Scoped]
[DependsOnExtras(typeof(IFoo))]
public partial class MyService { }

[Cover<MyService>]
public partial class MyServiceTests { }";

        var act = () => CompileWithCover(source);
        act.Should().NotThrow("single-type DependsOn params arg must continue to work");
    }

    #endregion

    #region TDIAG04 — GeneratedCode constructor intent

    /// <summary>
    /// Reproduces the pre-1.7.3 false positive: a service whose constructor was generated by
    /// IoCTools (tagged [GeneratedCode("IoCTools", ...)]) but has no direct lifetime attribute
    /// — e.g. a Keel LoggedHandler&lt;T&gt; subclass that inherits the base class's generated ctor.
    /// HasConstructorGenerationIntent previously returned false, causing TDIAG04 to fire incorrectly.
    /// </summary>
    [Fact]
    public void TDIAG04_GeneratedCodeConstructor_DoesNotFireFalsePositive()
    {
        // Compile the "production" assembly first. The generator runs and emits the
        // [GeneratedCode("IoCTools", ...)] constructor on LoggedHandlerBase.
        // LoggedHandlerBase has [Scoped] + [DependsOn<IDep>] → generator emits a constructor
        // tagged [GeneratedCode("IoCTools", ...)].
        var baseSource = @"
using IoCTools.Abstractions.Annotations;

namespace Keel;

public interface IDep { }

[Scoped]
[DependsOn<IDep>]
public abstract partial class LoggedHandlerBase { }";

        var baseResult = SourceGeneratorTestHelper.CompileWithGenerator(
            baseSource,
            analyzerBuildProperties: new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)
            {
                ["build_property.IsTestProject"] = "false"
            });
        baseResult.CompilationDiagnostics
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .Should().BeEmpty("base assembly must compile cleanly");

        using var baseStream = new System.IO.MemoryStream();
        var baseEmit = baseResult.Compilation.Emit(baseStream);
        baseEmit.Success.Should().BeTrue(string.Join(System.Environment.NewLine, baseEmit.Diagnostics));
        var baseReference = MetadataReference.CreateFromImage(baseStream.ToArray());

        // Compile the "handler" assembly: MyHandler derives from LoggedHandlerBase (which has the
        // [GeneratedCode("IoCTools")] constructor requiring IDep) but has no direct IoCTools attrs.
        // MyHandler explicitly forwards the base constructor to avoid CS7036.
        var handlerSource = @"
namespace App;

public class MyHandler : Keel.LoggedHandlerBase
{
    public MyHandler(Keel.IDep dep) : base(dep) { }
}";

        var handlerResult = SourceGeneratorTestHelper.CompileWithGenerator(
            handlerSource,
            analyzerBuildProperties: new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)
            {
                ["build_property.IsTestProject"] = "false"
            },
            additionalMetadataReferences: new MetadataReference[] { baseReference });
        handlerResult.CompilationDiagnostics
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .Should().BeEmpty("handler assembly must compile cleanly");

        using var handlerStream = new System.IO.MemoryStream();
        var handlerEmit = handlerResult.Compilation.Emit(handlerStream);
        handlerEmit.Success.Should().BeTrue(string.Join(System.Environment.NewLine, handlerEmit.Diagnostics));
        var handlerReference = MetadataReference.CreateFromImage(handlerStream.ToArray());

        // Test project: covers MyHandler. Pre-fix: TDIAG04 fires because HasConstructorGenerationIntent
        // returns false for MyHandler (no direct IoCTools attrs, no [GeneratedCode] on MyHandler itself).
        // But MyHandler's own constructor has [GeneratedCode("IoCTools")] — wait, actually it doesn't
        // because we wrote it manually. The real regression is for services where the ONLY constructor
        // carries [GeneratedCode("IoCTools")] because IoCTools generated it in a prior compilation pass.
        //
        // Simulate that by covering the base class directly: LoggedHandlerBase has only its
        // generated constructor (tagged [GeneratedCode("IoCTools")]). Pre-fix: TDIAG04 fired on it.
        // Post-fix: HasConstructorGenerationIntent detects the tag and returns true.
        var testSource = @"
using IoCTools.Testing.Annotations;

[Cover<Keel.LoggedHandlerBase>]
public partial class LoggedHandlerBaseTests { }";

        var iocTestingAssembly = typeof(IoCTools.Testing.Annotations.CoverAttribute<>).Assembly;
        var testResult = SourceGeneratorTestHelper.CompileWithGenerator(
            testSource,
            analyzerBuildProperties: new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)
            {
                ["build_property.IsTestProject"] = "true"
            },
            additionalMetadataReferences: new MetadataReference[]
            {
                baseReference,
                MetadataReference.CreateFromFile(iocTestingAssembly.Location),
                MetadataReference.CreateFromFile(typeof(FactAttribute).Assembly.Location)
            });

        testResult.Diagnostics
            .Where(d => d.Id == "TDIAG04")
            .Should().BeEmpty(
                "service with [GeneratedCode(\"IoCTools\")] constructor must not emit false TDIAG04");
    }

    #endregion

    private static GeneratorTestResult CompileWithCover(
        string source,
        bool isTestProject = true,
        MetadataReference[]? additionalMetadataReferences = null)
    {
        var iocTestingAssembly = typeof(IoCTools.Testing.Annotations.CoverAttribute<>).Assembly;
        MetadataReference[] additionalMetadata = { MetadataReference.CreateFromFile(iocTestingAssembly.Location) };

        try
        {
            var moqAssembly = Assembly.Load("Moq");
            additionalMetadata = additionalMetadata
                .Concat(new[] { MetadataReference.CreateFromFile(moqAssembly.Location) })
                .ToArray();
        }
        catch { }

        additionalMetadata = additionalMetadata
            .Concat(new[] { MetadataReference.CreateFromFile(typeof(FactAttribute).Assembly.Location) })
            .ToArray();

        if (additionalMetadataReferences is { Length: > 0 })
        {
            additionalMetadata = additionalMetadata
                .Concat(additionalMetadataReferences)
                .ToArray();
        }

        return SourceGeneratorTestHelper.CompileWithGenerator(
            source,
            analyzerBuildProperties: new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)
            {
                ["build_property.IsTestProject"] = isTestProject ? "true" : "false"
            },
            additionalMetadataReferences: additionalMetadata);
    }
}
